### ISSUE TITLE
Bug eller feature i linjediagrammet?

### ISSUE THREAD

**Issue by palundqv** [silverknet/ivis24-9-proj#16]
När man lägger musen över linjediagrammet i country view så kommrer det fram en liten vit ruta ovanför? Är det tanken att det ska bli en feature eller är det en bug?
![Screenshot (98)](https://github.com/silverknet/ivis24-9-proj/assets/61392121/c0b7e53e-8013-49f5-84de-dab71b460c3a)

**Comment by lallstedters** [comment]
Hmmm, placeringen är inte perfekt men det bör anses som en feature och är tänkt att va där! 
![image](https://github.com/silverknet/ivis24-9-proj/assets/70377036/cd7ddacd-140f-425b-a70f-33437f868dd4)

Hos mig, och vad jag trodde gällde hos alla, så har den text! Ksk är att din text blivit vit pga darkmode? Den ska visa mer exkata värden on hover är tanken.

**Comment by lallstedters** [comment]
Placeringen var lite lazy och är baserad på skärmcoordinater, borde nog ändras så att den istället är baserad på grafens placering

**Comment by palundqv** [comment]
Okej men då är det på G.

**Comment by silverknet** [comment]
tror den måste anpassas för dark mode också
